<?xml version="1.0" encoding="UTF-8"?>
<refentry xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svg="http://www.w3.org/2000/svg" xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:db="http://docbook.org/ns/docbook" xmlns:scilab="http://www.scilab.org" xml:lang="ja" xml:id="errcatch">
    <refnamediv>
        <refname>errcatch</refname>
        <refpurpose>エラーの捕捉</refpurpose>
    </refnamediv>
    <refsynopsisdiv>
        <title>呼出し手順</title>
        <synopsis>errcatch(n [,'action'] [,'option'])
            errcatch()
        </synopsis>
    </refsynopsisdiv>
    <refsection>
        <title>引数</title>
        <variablelist>
            <varlistentry>
                <term>n</term>
                <listitem>
                    <para>整数</para>
                </listitem>
            </varlistentry>
            <varlistentry>
                <term>action, option</term>
                <listitem>
                    <para>文字列</para>
                </listitem>
            </varlistentry>
        </variablelist>
    </refsection>
    <refsection>
        <title>説明</title>
        <para>
          <function>errcatch</function> は,
          <literal>n</literal>型のエラーが発生した時に
          実行される "アクション" (エラーハンドラ)を指定します,
        </para>
        <para>
          <varname>n</varname> は以下の意味を有します:
        </para>
        <para>
          <varname>n</varname><literal>&gt;0</literal>の場合, <varname>n</varname> は
          捕捉するエラー番号となります.
        </para>
        <para>
          <varname>n</varname><literal>&lt;0</literal> の場合,全てのエラーが捕捉されます.
        </para>
        <para>
          <varname>action</varname>は以下の文字列のどれかとなります:
        </para>
        <variablelist>
            <varlistentry>
                <term>"pause"</term>
                <listitem>
                    <para>
                      誤差を捕捉した際に pause が実行されます.
                      このオプションはデバッグの際に有用です.
                      カレントのコンテキストで情報を取得するには
                      <code>whereami()</code>を使用してください.
                    </para>
                </listitem>
            </varlistentry>
            <varlistentry>
                <term>"continue"</term>
                <listitem>
                    <para>
                      関数または実行ファイルないの次の命令が実行され,
                      カレントの命令は無視されます.
                      <link linkend="iserror">iserror</link>関数により,
                      エラーが発生したかどうかを調べることが可能です.できるだけ早く
                      <link linkend="errclear">errclear</link>関数によりエラーをクリアすることを
                      忘れないようにしてください.
                      このオプションはエラーからの回復の際に有用です.
                      多くの場合,
                      <link linkend="execstr">execstr</link> 関数または
                      <link linkend="try">try</link>制御構造を使用することにより
                      <literal>errcatch(n,"continue",..)</literal>を
                      置換することができます.
                    </para>
                </listitem>
            </varlistentry>
            <varlistentry>
                <term>"kill"</term>
                <listitem>
                    <para>デフォルトのモードであり,全ての実行中の関数の実行が破棄され,
                        Scilabの処理はレベル0プロンプトに戻ります.
                    </para>
                </listitem>
            </varlistentry>
            <varlistentry>
                <term>"stop"</term>
                <listitem>
                    <para>
                        カレントのScilabセッションを中断します(Scilabが外部プログラムからコールされた時に有用).
                    </para>
                </listitem>
            </varlistentry>
        </variablelist>
        <para>
          <varname>option</varname> は中断時のエラーメッセージである
          文字列 <literal>'nomessage'</literal> です.
        </para>
        <para>
          デフォルトモードに戻すためには,
          <code>errcatch(-1,"kill")</code> または
          <code>errcatch(-1)</code>と入力してください.
          <code>errcatch()</code> は以前使用されていた<code>errcatch(-1)</code>と
            等価です. 
        </para>
        <para/>
        <para>
          <function>errcatch</function>のアクションはカレントの評価コンテキスト
          (function, exec, pause) およびサブレベル全体に適用されます.
          あるサブレベル内で<function>errcatch</function>を2回コールすると
          このサブレベルでの最初のコールが隠蔽され,
          最初の関数コールの効果は削除されます.
        </para>
        <para> 
          Scilab関数または exec のコンテキスト内でコールされた場合,
          <function>errcatch</function>は,関数のリターンの時に自動的にリセットされます.
        </para>
    </refsection>
    <refsection>
        <title>例</title>
        <programlisting role="example"><![CDATA[ 
errcatch(144,"continue")
2/"foo"
disp(a) // Without the errcatch, this line would not be executed

errcatch(-1,"kill") // Come back in the normal mode
errcatch(144,"pause")
2/"foo" // Enter in "pause" mode

errcatch(27,'continue','nomessage')
b=2/0 // No error message but b will not exist
 ]]></programlisting>
    </refsection>
    <refsection role="see also">
        <title>参照</title>
        <simplelist type="inline">
            <member>
                <link linkend="try">try</link>
            </member>
            <member>
                <link linkend="errclear">errclear</link>
            </member>
            <member>
                <link linkend="iserror">iserror</link>
            </member>
            <member>
                <link linkend="whereami">whereami</link>
            </member>
            <member>
                <link linkend="execstr">execstr</link>
            </member>
            <member>
                <link linkend="exec">exec</link>
            </member>
            <member>
                <link linkend="pause">pause</link>
            </member>
        </simplelist>
    </refsection>
</refentry>
